# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://www.youtube.com/")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.NAME, "search_query").click()
    self.driver.find_element(By.NAME, "search_query").send_keys("花芽すみれ")
    self.driver.find_element(By.NAME, "search_query").send_keys(Keys.ENTER)
  
